version: '3.1'

services:

  db:
    image: mysql
    container_name: mysql
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: pass
    ports:
        - '3306:3306'
    volumes: 
        - ./mysql-init-files:/docker-entrypoint-initdb.d
